### ISSUE TITLE
重新回来标签页后的页面上的数据不见了

### ISSUE THREAD

**Issue by mendellin** [lqsong/admin-antd-react#3]
您好，当打开多个标签页后，在其中一个标签页随便输入一些数据，然后打开其他标签页，然后再回来第1个标签页，之前输入的数据不见了。要如何解决这个问题呢？谢谢。

**Comment by lqsong** [comment]
此框架的标签页类似于快捷导航没有你说的这个缓存，如果需要你可以自己进行扩展，比如使用 "react-activation"
